# Generated by Django 4.2.7 on 2025-07-13 06:39

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=uploader.models.upload_to, validators=[uploader.models.validate_file_type, uploader.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento CV',
                'verbose_name_plural': 'Documentos CV',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
